### ISSUE TITLE
Remove jobs.toggl.com/toggldesktop

### ISSUE THREAD

**Issue by kadrihvl** [toggl/jobs_toggl_com#73]
One user posted that https://jobs.toggl.com/toggldesktop/  is not loading it’s external resources… I guess as we are not looking someone for the desktop team, we should remove this page?

![toggle joboffer bug](https://cloud.githubusercontent.com/assets/12407134/18623556/7852092e-7e47-11e6-9540-4c17d1067a55.png)

**Comment by syko** [comment]
Did not remove the page but fixed it.
Instead of removing pages we usually just change it to say the test is finished so any external links or bookmarks won't break.
