### ISSUE TITLE
New campaign for hiring mobile developers

### ISSUE THREAD

**Issue by willsb** [toggl/jobs_toggl_com#74]
> **Mobile Developer**

> You know iPhone development so well Apple calls you when they have a bug. You think that Swift is the best thing that has happened to iPhone development since AFNetworking, so you know it inside out.
> 
> You can work from anywhere in the world, as long as your English communication is great.
> 
> Your gross salary will be €42,000 – €45,000, based on experience. We'll send a Toggl t-shirt and swag if you do well on the test.

The actual test is yet to be merged -> toggl/jobbl_private#277

cc @pe0ny and @amulware

**Comment by pe0ny** [comment]
Image:
![superday-mobile-dev](https://cloud.githubusercontent.com/assets/5064445/18876315/d1f14f18-84d1-11e6-9f93-e32e9a0bf6e2.jpg)
